merchant/modules/base/controllers/LocalDistributionAreaController.php
<?php

namespace addons\TinyShop\merchant\modules\base\controllers;

use Yii;
use common\traits\MerchantCurd;
use addons\TinyShop\common\models\base\LocalDistributionArea;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * Class LocalDistributionAreaController
 * @package addons\TinyShop\merchant\modules\base\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class LocalDistributionAreaController extends BaseController
{
    use MerchantCurd;

    /**
     * @var LocalDistributionArea
     */
    public $modelClass = LocalDistributionArea::class;

    /**
     * 编辑/创建
     *
     * @return mixed
     */
    public function actionEdit()
    {
        $model = $this->findModel($this->getMerchantId());
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['edit']);
        }

        return $this->render($this->action->id, [
            'model' => $model,
        ]);
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return \yii\db\ActiveRecord
     */
    protected function findModel($id)
    {
        /* @var $model \yii\db\ActiveRecord */
        if (empty(($model = $this->modelClass::findOne(['merchant_id' => $id])))) {
            $model = new $this->modelClass;
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

merchant/modules/base/controllers/LocalDistributionConfigController.php
<?php

namespace addons\TinyShop\merchant\modules\base\controllers;

use Yii;
use common\helpers\ArrayHelper;
use common\helpers\DateHelper;
use common\enums\StatusEnum;
use common\traits\MerchantCurd;
use addons\TinyShop\merchant\forms\LocalDistributionConfigForm;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * Class LocalDistributionAreaController
 * @package addons\TinyShop\merchant\modules\base\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class LocalDistributionConfigController extends BaseController
{
    use MerchantCurd;

    /**
     * @var LocalDistributionConfigForm
     */
    public $modelClass = LocalDistributionConfigForm::class;

    /**
     * 编辑/创建
     *
     * @return mixed
     */
    public function actionEdit()
    {
        $model = $this->findModel($this->getMerchantId());
        $model->is_start = StatusEnum::ENABLED;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->message('保存成功', $this->redirect(['edit']));
        }

        $forenoon_start = DateHelper::formatHours(ArrayHelper::numBetween(0, 43200, true, 1800));
        $forenoon_end = DateHelper::formatHours(ArrayHelper::numBetween(0, 43200, true, 1800));
        $afternoon_start = DateHelper::formatHours(ArrayHelper::numBetween(43200, 86400, true, 1800));
        $afternoon_end = DateHelper::formatHours(ArrayHelper::numBetween(43200, 86400, true, 1800));

        return $this->render($this->action->id, [
            'model' => $model,
            'forenoon_start' => $forenoon_start,
            'forenoon_end' => $forenoon_end,
            'afternoon_start' => $afternoon_start,
            'afternoon_end' => $afternoon_end,
        ]);
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return \yii\db\ActiveRecord
     */
    protected function findModel($id)
    {
        /* @var $model \yii\db\ActiveRecord */
        if (empty(($model = $this->modelClass::findOne(['merchant_id' => $id, 'is_start' => StatusEnum::ENABLED])))) {
            $model = new $this->modelClass;
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

merchant/modules/base/controllers/LocalDistributionMemberController.php
<?php

namespace addons\TinyShop\merchant\modules\base\controllers;

use Yii;
use common\enums\StatusEnum;
use common\models\base\SearchModel;
use common\traits\MerchantCurd;
use addons\TinyShop\common\models\base\LocalDistributionMember;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * Class LocalDistributionMemberController
 * @package addons\TinyShop\merchant\modules\base\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class LocalDistributionMemberController extends BaseController
{
    use MerchantCurd;

    /**
     * @var LocalDistributionMember
     */
    public $modelClass = LocalDistributionMember::class;

    /**
     * 首页
     *
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionIndex()
    {
        $searchModel = new SearchModel([
            'model' => $this->modelClass,
            'scenario' => 'default',
            'partialMatchAttributes' => ['title'], // 模糊查询
            'defaultOrder' => [
                'id' => SORT_DESC,
            ],
            'pageSize' => $this->pageSize,
        ]);

        $dataProvider = $searchModel
            ->search(Yii::$app->request->queryParams);
        $dataProvider->query
            ->andWhere(['status' => StatusEnum::ENABLED])
            ->andWhere(['merchant_id' => $this->getMerchantId()]);

        return $this->render($this->action->id, [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }
}

merchant/modules/base/views/local-distribution-area/edit.php
<?php

use yii\widgets\ActiveForm;
use common\helpers\Url;

$this->title = '本地配送地区';
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>

<div class="row">
    <div class="col-sm-12">
        <div class="nav-tabs-custom">
            <?= $this->render('../common/_express_nav', [
                'type' => 'local-distribution',
            ]) ?>
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="tab-pane active">
                        <nav class="goods-nav">
                            <ul>
                                <li><a href="<?= Url::to(['local-distribution-member/index']) ?>">配送人员</a></li>
                                <li><a href="<?= Url::to(['local-distribution-config/edit']) ?>">配送费用</a></li>
                                <li class="selected"><a href="<?= Url::to(['local-distribution-area/edit']) ?>">本地配送地区</a></li>
                            </ul>
                        </nav>
                        <div class="box">
                            <?php $form = ActiveForm::begin([
                                'fieldConfig' => [
                                    'template' => "<div class='col-sm-2 text-right'>{label}</div><div class='col-sm-10'>{input}\n{hint}\n{error}</div>",
                                ],
                            ]); ?>
                            <!-- /.box-header -->
                            <div class="box-body table-responsive">
                                <div class="form-group">
                                    <div class="col-sm-2 text-right">
                                        <label class="control-label">支持地区</label>
                                    </div>
                                    <div class="col-sm-10">
                                        <a class="js-select-city btn btn-primary btn-sm" data-toggle="modal" data-target="#ajaxModalLgForExpress">指定地区城市</a>
                                        <div class="help-block"></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-2 text-right">
                                        <label class="control-label">已选择地区</label>
                                    </div>
                                    <div class="col-sm-10">
                                        <span class="js-region-info region-info"></span>
                                        <div class="help-block"></div>
                                    </div>
                                </div>
                                <!-- /.box-body -->
                            </div>
                            <div class="box-footer text-center">
                                <button class="btn btn-primary" type="submit">保存</button>
                            </div>

                            <!-- 地区选择工具 -->
                            <?= \common\widgets\area\Area::widget([
                                'model' => $model,
                                'form' => $form,
                                'provincesName' => 'province_ids',
                                'cityName' => 'city_ids',
                                'areaName' => 'area_ids',
                                'level' => 3
                            ]) ?>

                            <?php ActiveForm::end(); ?>
                            <!-- /.box -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>